env:
  node: true
  browser: true
  es6: true
  jest: true

extends:
  - bayathy
  - plugin:storybook/recommended

plugins:
  - jest-dom
  - testing-library

parserOptions:
  ecmaFeatures:
    jsx: true

parser: "@typescript-eslint/parser"
