env:
  node: true
  browser: true
  es6: true
  jest: true

extends:
  - "@bayathy/eslint-config"
  - "@bayathy/eslint-config-react"
  - "@bayathy/eslint-config-jest"
  - plugin:storybook/recommended

plugins:
  - jest-dom
  - testing-library

parserOptions:
  ecmaFeatures:
    jsx: true

parser: "@typescript-eslint/parser"

rules:
  unicorn/prevent-abbreviations: off
